project_id = "xtailgacbmhdtdxnqjdv"

[functions.rpc-proxy]
verify_jwt = false

[functions.price-api]
verify_jwt = false

[functions.automated-rewards]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.pulsex-graphql]
verify_jwt = false
