// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtailgacbmhdtdxnqjdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YWlsZ2FjYm1oZHRkeG5xamR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4OTM1MTksImV4cCI6MjA2NjQ2OTUxOX0.UZeO_YzLki7jWoXTYGoV0LIn4V_rifgkY5Vam1sArTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);